TASK:
  "ins_seg_3d"
MODEL:
  TYPE: "CUSTOM"
  CUSTOM:
    classifier:
      type: "RegionClassifier"
      backbone:
        type: "PointNet2SSG"
        in_channels: 3
        num_centroids: (64, 0)
        radius: (0.2, -1.0)
        num_neighbours: (32, -1)
        sa_channels: ((64, 64, 128), (128, 128, 128))
        fp_channels: ((128, 128), (64, 64, 64))
        num_fp_neighbours: (0, 3)
      head:
        type: "ConcatHead"
        in_channels: 64
INPUT:
  IN_CHANNELS: 3
DATASET:
  ROOT_DIR: "data/partnet/ins_seg_h5_for_detection"
  TYPE: "PartNetInsSeg"
  PartNetInsSeg:
    TRAIN:
      split: "train"
      shape: ["Chair","Lamp","StorageFurniture"]
      stage1: "fusion"
      level: 3
    VAL:
      split: "val"
      shape: "Chair"
      level: 3
DATALOADER:
  NUM_WORKERS: 0
  KWARGS:
    num_centroids: 128
    radius: 0.2
    num_neighbours: 512
    with_renorm: True
    with_resample: False
    with_shift: False
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "StepLR"
  StepLR:
    gamma: 0.5
    step_size: 15
  CLIP_LR: 1e-5
  MAX_EPOCH: 120
TRAIN:
  BATCH_SIZE: 6  # 12
  LOG_PERIOD: 10
  VAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
TEST:
  BATCH_SIZE: 1
